### ISSUE TITLE
Fails to compile on Windows due to stoi error

### ISSUE THREAD

**Issue by ArlinTawzer** [mlacapra/Lacapra_CSCI2270_FinalProject#1]
I don't know why but windows does not like the stoi. I'm going to try and troubleshoot.

**Comment by mlacapra** [comment]
The ReadMe does say that the program should be run on Mac OS X with Xcode, but i'll try and see if I can make a fix so you can run it on your machine

**Comment by ArlinTawzer** [comment]
Stoi error is not a problem in compiling on the virtual machine

**Comment by mlacapra** [comment]
Glad to hear it :)
